daikin_resume_program:
  description: >-
    Return to the schedule from manual mode
  fields:
    entity_id:
      description: thermostat on which to resume the schedule.
      example: "climate.kitchen"
daikin_set_fan_schedule:
  description: >-
    Set a schedule for running the HVAC fan to clean the air
  fields:
    entity_id:
      description: thermostat on which to resume the schedule.
      example: "climate.kitchen"
    start_time:
      description: is the beginning of the schedule per day.  It is an integer value where every 15 minutes from 00:00 is 1 (each hour = 4)
      example: "32"
    end_time:
      description: is the end of the schedule per day.  It is an integer value where every 15 minutes from 00:00 is 1 (each hour = 4)
      example: "72"
    interval:
      description:  the run time per hour of the schedule. Options are - on the full time (0), 5mins (1), 15mins (2), 30mins (3), and 45mins (4)
      example: "2"
      